import type { Metadata } from "next"
import { Bebas_Neue, Nunito, Geist_Mono } from "next/font/google"
import "./globals.css"

// Heading font
const bebas = Bebas_Neue({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400",
})

// Body font
const nunito = Nunito({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${bebas.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
